# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='createdAt',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='rating',
        ),
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.IntegerField(),
        ),
    ]
