# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20171214_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
