# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
