# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20171215_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='author',
        ),
    ]
